codecparsers: Fix link error when linking to libyami_codecparser
Attempting to link directly to libyami_codecparser.la results
in undefined reference to yamiLogFn and yamiLogFlag.

It is necessary to link the libyami_common library to
libyami_codecparser since common/log.h is included by, at
least, bitreader.h->gst/gst.h and vp9parser.h.

Also, this requires that 'common' appear before 'codecparsers' in
the top level Makefile.am SUBDIRS variable.

Signed-off-by: U. Artie Eoff <ullysses.a.eoff@intel.com>