vaapi: requires libyami_common
Fix external static linking:
 undefined reference to `YamiMediaCodec::getPlaneResolution

Signed-off-by: U. Artie Eoff <ullysses.a.eoff@intel.com>